# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2020-09-28"
# docker_image = "jjy0/ckb-capsule-recipe-rust:2020-9-28"

# capsule version
version = "0.6.0 b850e01"
# path of deployment config file
deployment = "deployment.toml"

[rust]
workspace_dir = "."
toolchain = "nightly-2021-08-16"
docker_image = "thewawar/ckb-capsule:2021-08-16"

[[contracts]]
name = "hide_email"
template_type = "Rust"
